export const colors = [
    { value: 'Blue', label: 'Blue' },
    { value: 'Green', label: 'Green' },
    { value: 'Red', label: 'Red' },
    { value: 'Yellow', label: 'Yellow' },
    { value: 'Purple', label: 'Purple' },
    { value: 'Orange', label: 'Brown' },
    { value: 'BlueGreen', label: 'Blue / Green' },
    { value: 'BlueRed', label: 'Blue / Red' },
    { value: 'BlueYellow', label: 'Blue / Yellow' },
    { value: 'BluePurple', label: 'Blue / Purple' },
    { value: 'BlueOrange', label: 'Blue / Brown' },
    { value: 'GreenRed', label: 'Green / Red' },
    { value: 'GreenYellow', label: 'Green / Yellow' },
    { value: 'GreenPurple', label: 'Green / Purple' },
    { value: 'GreenOrange', label: 'Green / Brown' },
    { value: 'RedYellow', label: 'Red / Yellow' },
    { value: 'RedPurple', label: 'Red / Purple' },
    { value: 'RedOrange', label: 'Red / Brown' },
    { value: 'YellowPurple', label: 'Yellow / Purple' },
    { value: 'YellowOrange', label: 'Yellow / Brown' },
    { value: 'PurpleOrange', label: 'Purple / Brown' },
    { value: 'BlueGreenRed', label: 'Blue / Green / Red' },
    { value: 'BlueGreenYellow', label: 'Blue / Green / Yellow' },
    { value: 'BlueGreenPurple', label: 'Blue / Green / Purple' },
    { value: 'BlueGreenOrange', label: 'Blue / Green / Brown' },
    { value: 'BlueRedYellow', label: 'Blue / Red / Yellow' },
    { value: 'BlueRedPurple', label: 'Blue / Red / Purple' },
    { value: 'BlueRedOrange', label: 'Blue / Red / Brown' },
    { value: 'BlueYellowPurple', label: 'Blue / Yellow / Purple' },
    { value: 'BlueYellowOrange', label: 'Blue / Yellow / Brown' },
    { value: 'BluePurpleOrange', label: 'Blue / Purple / Brown' },
    { value: 'GreenRedYellow', label: 'Green / Red / Yellow' },
    { value: 'GreenRedPurple', label: 'Green / Red / Purple' },
    { value: 'GreenRedOrange', label: 'Green / Red / Brown' },
    { value: 'GreenYellowPurple', label: 'Green / Yellow / Purple' },
    { value: 'GreenYellowOrange', label: 'Green / Yellow / Brown' },
    { value: 'GreenPurpleOrange', label: 'Green / Purple / Brown' },
    { value: 'RedYellowPurple', label: 'Red / Yellow / Purple' },
    { value: 'RedYellowOrange', label: 'Red / Yellow / Brown' },
    { value: 'RedPurpleOrange', label: 'Red / Purple / Brown' },
    { value: 'YellowPurpleOrange', label: 'Yellow / Purple / Brown' },
    { value: 'All', label: 'All' }
];

export const rarities = [
  'Common',
  'Rare',
  'Ultra-Rare',
  'Epic',
  'Legendary',
  'Mythic',
  'Doomed',
]

export const roles = [
  'Assassin',
  'Defender',
  'Generator',
  'Mage',
  'Striker',
  'Support',
  'Warlock',
  'Warmaster',
  'Warrior'
]

export const trait_codes = [
  'aflame',
  'agile',
  'airbrand',
  'airheart',
  'airlink',
  'airspirit',
  'alert',
  'arcane',
  'armored',
  'armorpiercing',
  'aspectofdeath',
  'aspectoffamine',
  'aspectofplague',
  'aspectofwar',
  'assassinate',
  'avenger',
  'beastbond',
  'beastslayer',
  'big',
  'blessed',
  'bloodsucking',
  'bullseye',
  'centaurbond',
  'centaurslayer',
  'chill',
  'chilltouch',
  'clobber',
  'clockwork',
  'cocoon',
  'compassion',
  'constructbond',
  'constructslayer',
  'cunning',
  'cursed',
  'daemonbond',
  'daemonicpact',
  'daemonslayer',
  'darkchannel',
  'darkfall',
  'deathtouch',
  'defender',
  'divineaura',
  'divinebond',
  'divineshield',
  'divineslayer',
  'doom',
  'dragonbond',
  'dragonslayer',
  'dragonvines',
  'dwarfbond',
  'dwarfslayer',
  'elementalbond',
  'elementalslayer',
  'elfbond',
  'elfslayer',
  'empowered',
  'ensoul',
  'exchangeattacktomagic',
  'eyeofkhetar',
  'fall',
  'fast',
  'feybond',
  'feyslayer',
  'fierycloak',
  'firebrand',
  'fireheart',
  'firelink',
  'fireproof',
  'firespirit',
  'flying',
  'frenzy',
  'frozensoul',
  'fullplate',
  'gardswrath',
  'gateguardian',
  'giantbond',
  'giantslayer',
  'goblinbond',
  'goblinslayer',
  'goblord',
  'graniteskin',
  'greedy',
  'grudge',
  'hacknslash',
  'huge',
  'humanbond',
  'humanslayer',
  'hunger',
  'icycloak',
  'immense',
  'immortal',
  'immune',
  'impervious',
  'indigestible',
  'inscribed',
  'insulated',
  'jinx',
  'kingswill',
  'knightbond',
  'knightslayer',
  'knockout',
  'leader',
  'lethaltoxin',
  'lifedrain',
  'lionstrength',
  'magearmor',
  'magicbrand',
  'magicheart',
  'magiclink',
  'magicspirit',
  'manashield',
  'manyheads',
  'marauderbond',
  'marauderslayer',
  'mechbond',
  'mechslayer',
  'merchant',
  'merfolkbond',
  'merfolkslayer',
  'miasma',
  'molten',
  'monsterbond',
  'monsterslayer',
  'mysticbond',
  'mysticslayer',
  'nagabond',
  'nagaslayer',
  'nastyteeth',
  'naturebrand',
  'natureheart',
  'naturelink',
  'naturespirit',
  'necromancy',
  'orcbond',
  'orclord',
  'orcslayer',
  'plaguetouch',
  'pyromania',
  'queensgrace',
  'rakshabond',
  'rakshaslayer',
  'regeneration',
  'reinforced',
  'roguebond',
  'rogueslayer',
  'sacrifice',
  'seedling',
  'shatter',
  'siege',
  'silence',
  'siphon',
  'slippery',
  'snare',
  'soullegion',
  'spikearmor',
  'spiritfire',
  'stalker',
  'stealthy',
  'stonebrand',
  'stoneheart',
  'stonelink',
  'stoneskin',
  'stonespirit',
  'stryxbond',
  'stryxslayer',
  'sturdy',
  'sunshine',
  'suppression',
  'taurosbond',
  'taurosslayer',
  'technomancy',
  'thickhead',
  'thorns',
  'trueshot',
  'undeadbond',
  'undeadslayer',
  'venomous',
  'virulence',
  'ward',
  'warded',
  'wargarebond',
  'wargareslayer',
  'waterbrand',
  'waterheart',
  'waterlink',
  'waterspirit',
  'wildfolkbond',
  'wildfolkslayer',
  'winterveil',
];