export const colors = [
    { value: 'Blue', label: 'Blue' },
    { value: 'Green', label: 'Green' },
    { value: 'Red', label: 'Red' },
    { value: 'Yellow', label: 'Yellow' },
    { value: 'Purple', label: 'Purple' },
    { value: 'Orange', label: 'Brown' },
    { value: 'BlueGreen', label: 'Blue / Green' },
    { value: 'BlueRed', label: 'Blue / Red' },
    { value: 'BlueYellow', label: 'Blue / Yellow' },
    { value: 'BluePurple', label: 'Blue / Purple' },
    { value: 'BlueOrange', label: 'Blue / Brown' },
    { value: 'GreenRed', label: 'Green / Red' },
    { value: 'GreenYellow', label: 'Green / Yellow' },
    { value: 'GreenPurple', label: 'Green / Purple' },
    { value: 'GreenOrange', label: 'Green / Brown' },
    { value: 'RedYellow', label: 'Red / Yellow' },
    { value: 'RedPurple', label: 'Red / Purple' },
    { value: 'RedOrange', label: 'Red / Brown' },
    { value: 'YellowPurple', label: 'Yellow / Purple' },
    { value: 'YellowOrange', label: 'Yellow / Brown' },
    { value: 'PurpleOrange', label: 'Purple / Brown' },
    { value: 'BlueGreenRed', label: 'Blue / Green / Red' },
    { value: 'BlueGreenYellow', label: 'Blue / Green / Yellow' },
    { value: 'BlueGreenPurple', label: 'Blue / Green / Purple' },
    { value: 'BlueGreenOrange', label: 'Blue / Green / Brown' },
    { value: 'BlueRedYellow', label: 'Blue / Red / Yellow' },
    { value: 'BlueRedPurple', label: 'Blue / Red / Purple' },
    { value: 'BlueRedOrange', label: 'Blue / Red / Brown' },
    { value: 'BlueYellowPurple', label: 'Blue / Yellow / Purple' },
    { value: 'BlueYellowOrange', label: 'Blue / Yellow / Brown' },
    { value: 'BluePurpleOrange', label: 'Blue / Purple / Brown' },
    { value: 'GreenRedYellow', label: 'Green / Red / Yellow' },
    { value: 'GreenRedPurple', label: 'Green / Red / Purple' },
    { value: 'GreenRedOrange', label: 'Green / Red / Brown' },
    { value: 'GreenYellowPurple', label: 'Green / Yellow / Purple' },
    { value: 'GreenYellowOrange', label: 'Green / Yellow / Brown' },
    { value: 'GreenPurpleOrange', label: 'Green / Purple / Brown' },
    { value: 'RedYellowPurple', label: 'Red / Yellow / Purple' },
    { value: 'RedYellowOrange', label: 'Red / Yellow / Brown' },
    { value: 'RedPurpleOrange', label: 'Red / Purple / Brown' },
    { value: 'YellowPurpleOrange', label: 'Yellow / Purple / Brown' },
    { value: 'All', label: 'All' }
];

export const rarities = [
  'Common',
  'Rare',
  'Ultra-Rare',
  'Epic',
  'Legendary',
  'Mythic',
  'Doomed',
]

export const roles = [
  'Assassin',
  'Defender',
  'Generator',
  'Mage',
  'Striker',
  'Support',
  'Warlock',
  'Warmaster',
  'Warrior'
]

export const traits = [
  { value: 'spikearmor',            label: "Absorb Power" },
  { value: 'cursed',                label: "Accursed" },
  { value: 'silence',               label: "Adagio" },
  { value: 'stoneskin',             label: "Aegis" },
  { value: 'aflame',                label: "Aflame" },
  { value: 'agile',                 label: "Agile" },
  { value: 'airbrand',              label: "Air Brand" },
  { value: 'airheart',              label: "Air Heart" },
  { value: 'airlink',               label: "Air Link" },
  { value: 'airspirit',             label: "Air Spirit" },
  { value: 'alert',                 label: "Alert" },
  { value: 'divineshield',          label: "Ancient Blessing" },
  { value: 'divineaura',            label: "Ancient Mysteries" },
  { value: 'nastyteeth',            label: "Angry Bear" },
  { value: 'magiclink',             label: "Anti-Magic" },
  { value: 'jinx',                  label: "Anti-Magic Sphere" },
  { value: 'feyslayer',             label: "Antiquity" },
  { value: 'aspectofwar',           label: "Apparition" },
  { value: 'waterspirit',           label: "Aquatic" },
  { value: 'winterveil',            label: "Aquatic Glory" },
  { value: 'arcane',                label: "Arcane" },
  { value: 'magiclink',             label: "Arcane Surge" },
  { value: 'armorpiercing',         label: "Armor Piercing" },
  { value: 'clockwork',             label: "Armor Plating" },
  { value: 'armored',               label: "Armor of Light" },
  { value: 'armored',               label: "Armored" },
  { value: 'aspectofdeath',         label: "Aspect of Death" },
  { value: 'aspectoffamine',        label: "Aspect of Famine" },
  { value: 'aspectofplague',        label: "Aspect of Plague" },
  { value: 'aspectofwar',           label: "Aspect of War" },
  { value: 'assassinate',           label: "Assassinate" },
  { value: 'divineaura',            label: "Aura of Power" },
  { value: 'avenger',               label: "Avenger" },
  { value: 'dwarfslayer',           label: "Axes of Doom" },
  { value: 'humanbond',             label: "Backup" },
  { value: 'immense',               label: "Ballistics" },
  { value: 'manashield',            label: "Banishment" },
  { value: 'spikearmor',            label: "Bardic Inspiration" },
  { value: 'natureheart',           label: "Barkskin" },
  { value: 'beastbond',             label: "Beast Bond" },
  { value: 'beastbond',             label: "Beast Shield" },
  { value: 'beastslayer',           label: "Beast Slayer" },
  { value: 'centaurslayer',         label: "Beast Spirit" },
  { value: 'big',                   label: "Big" },
  { value: 'nagaslayer',            label: "Big Teeth" },
  { value: 'hunger',                label: "Black Hunger" },
  { value: 'divineshield',          label: "Blessing of Anu" },
  { value: 'doom',                  label: "Blessing of Gaard" },
  { value: 'reinforced',            label: "Blood and Glory" },
  { value: 'frenzy',                label: "Bloodlust" },
  { value: 'bloodsucking',          label: "Bloodsucking" },
  { value: 'bloodsucking',          label: "Bloodthirsty" },
  { value: 'dragonvines',           label: "Bloody Boughs" },
  { value: 'soullegion',            label: "Boo!" },
  { value: 'merchant',              label: "Bountyhunter" },
  { value: 'airbrand',              label: "Bright Death" },
  { value: 'blessed',               label: "Brilliant Aura" },
  { value: 'taurosbond',            label: "Bull General" },
  { value: 'orclord',               label: "Bullish Vigor" },
  { value: 'bullseye',              label: "Bullseye" },
  { value: 'stonebrand',            label: "Buried Hatred" },
  { value: 'firebrand',             label: "Burning Hatred" },
  { value: 'undeadbond',            label: "Call Bones" },
  { value: 'exchangeattacktomagic', label: "Call Darkness" },
  { value: 'daemonslayer',          label: "Call Doom" },
  { value: 'firespirit',            label: "Call Fire" },
  { value: 'waterbrand',            label: "Call Ice" },
  { value: 'magearmor',             label: "Call Light" },
  { value: 'natureheart',           label: "Call Nature" },
  { value: 'stonespirit',           label: "Call Stone" },
  { value: 'molten',                label: "Cataclysm" },
  { value: 'blessed',               label: "Celestial Currents" },
  { value: 'divineshield',          label: "Celestial Sage" },
  { value: 'divineshield',          label: "Celestial Shield" },
  { value: 'centaurbond',           label: "Centaur Bond" },
  { value: 'centaurbond',           label: "Centaur Shield" },
  { value: 'centaurslayer',         label: "Centaur Slayer" },
  { value: 'airspirit',             label: "Chaos Storm" },
  { value: 'inscribed',             label: "Chaos Wave" },
  { value: 'divinebond',            label: "Child of Sky" },
  { value: 'chill',                 label: "Chill" },
  { value: 'chilltouch',            label: "Chill Touch" },
  { value: 'chilltouch',            label: "Chill of Death" },
  { value: 'icycloak',              label: "Chilling Aura" },
  { value: 'divineshield',          label: "Cleanse" },
  { value: 'clobber',               label: "Clobber" },
  { value: 'clockwork',             label: "Clockwork" },
  { value: 'kingswill',             label: "Commander" },
  { value: 'compassion',            label: "Compassion" },
  { value: 'molten',                label: "Conflagration" },
  { value: 'constructbond',         label: "Construct Bond" },
  { value: 'constructbond',         label: "Construct Shield" },
  { value: 'constructslayer',       label: "Construct Slayer" },
  { value: 'siphon',                label: "Contagion" },
  { value: 'miasma',                label: "Corruption" },
  { value: 'defender',              label: "Counterattack" },
  { value: 'waterspirit',           label: "Crashing Wave" },
  { value: 'ensoul',                label: "Creeping Doom" },
  { value: 'graniteskin',           label: "Crystallize" },
  { value: 'cunning',               label: "Cunning" },
  { value: 'ward',                  label: "Curse of Madness" },
  { value: 'cursed',                label: "Cursed Touch" },
  { value: 'daemonbond',            label: "Daemon Bond" },
  { value: 'daemonbond',            label: "Daemon Shield" },
  { value: 'daemonslayer',          label: "Daemon Slayer" },
  { value: 'daemonicpact',          label: "Daemonic Pact" },
  { value: 'daemonslayer',          label: "Daemonic Rage" },
  { value: 'cursed',                label: "Dark Ancestry" },
  { value: 'darkchannel',           label: "Dark Channel" },
  { value: 'daemonicpact',          label: "Dark Covenant" },
  { value: 'magicbrand',            label: "Dark Death" },
  { value: 'aspectofdeath',         label: "Dark Fury" },
  { value: 'magicbrand',            label: "Dark Hatred" },
  { value: 'centaurslayer',         label: "Dark Hunger" },
  { value: 'venomous',              label: "Dark Venom" },
  { value: 'darkfall',              label: "Darkfall" },
  { value: 'darkfall',              label: "Darkness" },
  { value: 'sunshine',              label: "Dawn’s Aura" },
  { value: 'airbrand',              label: "Deadly Flock" },
  { value: 'miasma',                label: "Deadly Waters" },
  { value: 'hunger',                label: "Death Below" },
  { value: 'aspectofdeath',         label: "Death Curse" },
  { value: 'trueshot',              label: "Death Ray" },
  { value: 'deathtouch',            label: "Death Touch" },
  { value: 'magicbrand',            label: "Deep Magic" },
  { value: 'reinforced',            label: "Deep Shield" },
  { value: 'avenger',               label: "Deep Strength" },
  { value: 'regeneration',          label: "Deep Vitality" },
  { value: 'bloodsucking',          label: "Deep Water" },
  { value: 'assassinate',           label: "Deep Wounds" },
  { value: 'defender',              label: "Defender" },
  { value: 'indigestible',          label: "Delirium" },
  { value: 'waterlink',             label: "Deluge" },
  { value: 'waterspirit',           label: "Depth Charge" },
  { value: 'kingswill',             label: "Desert King" },
  { value: 'darkfall',              label: "Destiny of Darkness" },
  { value: 'fierycloak',            label: "Destiny of Flame" },
  { value: 'frozensoul',            label: "Destiny of Ice" },
  { value: 'sunshine',              label: "Destiny of Light" },
  { value: 'seedling',              label: "Destiny of Nature" },
  { value: 'graniteskin',           label: "Destiny of Stone" },
  { value: 'spikearmor',            label: "Dexterous" },
  { value: 'silence',               label: "Dissonance" },
  { value: 'divineaura',            label: "Divine Aura" },
  { value: 'divinebond',            label: "Divine Bond" },
  { value: 'divineshield',          label: "Divine Right" },
  { value: 'divinebond',            label: "Divine Shield" },
  { value: 'divineslayer',          label: "Divine Slayer" },
  { value: 'divineaura',            label: "Divinity" },
  { value: 'agile',                 label: "Dodge" },
  { value: 'doom',                  label: "Doom" },
  { value: 'aspectofdeath',         label: "Doom Aura" },
  { value: 'dragonbond',            label: "Dragon Bond" },
  { value: 'dragonbond',            label: "Dragon Boon" },
  { value: 'dragonbond',            label: "Dragon Shield" },
  { value: 'dragonslayer',          label: "Dragon Slayer" },
  { value: 'dragonvines',           label: "Dragon Vines" },
  { value: 'divineaura',            label: "Dragon's Blessing" },
  { value: 'manyheads',             label: "Dragon's Grace" },
  { value: 'undeadslayer',          label: "Drowned Crew" },
  { value: 'darkchannel',           label: "Dusk’s Aura" },
  { value: 'dwarfbond',             label: "Dwarf Bond" },
  { value: 'dwarfbond',             label: "Dwarf Shield" },
  { value: 'dwarfslayer',           label: "Dwarf Slayer" },
  { value: 'giantbond',             label: "Dwarven Armor" },
  { value: 'soullegion',            label: "Dwarven Doom" },
  { value: 'giantslayer',           label: "Dwarven Mettle" },
  { value: 'alert',                 label: "Eagle Eye" },
  { value: 'shatter',               label: "Earthquake" },
  { value: 'technomancy',           label: "Electrified Plating" },
  { value: 'elementalbond',         label: "Elemental Bond" },
  { value: 'elementalbond',         label: "Elemental Shield" },
  { value: 'elementalslayer',       label: "Elemental Slayer" },
  { value: 'elfbond',               label: "Elf Bond" },
  { value: 'elfbond',               label: "Elf Shield" },
  { value: 'elfslayer',             label: "Elf Slayer" },
  { value: 'dragonvines',           label: "Elven Kin" },
  { value: 'elfbond',               label: "Elven Sentries" },
  { value: 'kingswill',             label: "Emperor's Blessing" },
  { value: 'empowered',             label: "Empowered" },
  { value: 'technomancy',           label: "Energize" },
  { value: 'ensoul',                label: "Ensoul" },
  { value: 'fireproof',             label: "Entrapment" },
  { value: 'feybond',               label: "Eternal Summer" },
  { value: 'avenger',               label: "Exemplar" },
  { value: 'siphon',                label: "Experiment" },
  { value: 'greedy',                label: "Extreme Greed" },
  { value: 'fall',                  label: "Fall" },
  { value: 'goblord',               label: "Familiar" },
  { value: 'fast',                  label: "Fast" },
  { value: 'regeneration',          label: "Fast Healing" },
  { value: 'beastbond',             label: "Feline Fury" },
  { value: 'deathtouch',            label: "Ferocity" },
  { value: 'feybond',               label: "Fey Bond" },
  { value: 'spiritfire',            label: "Fey Link" },
  { value: 'feybond',               label: "Fey Shield" },
  { value: 'feyslayer',             label: "Fey Slayer" },
  { value: 'feybond',               label: "Fey Touch" },
  { value: 'aflame',                label: "Fey Vengeance" },
  { value: 'feyslayer',             label: "Feyblade" },
  { value: 'fierycloak',            label: "Fiery Cloak" },
  { value: 'firebrand',             label: "Fiery Death" },
  { value: 'fierycloak',            label: "Fire Aura" },
  { value: 'firebrand',             label: "Fire Brand" },
  { value: 'fireheart',             label: "Fire Heart" },
  { value: 'firelink',              label: "Fire Link" },
  { value: 'firespirit',            label: "Fire Spirit" },
  { value: 'pyromania',             label: "Fireblade" },
  { value: 'firelink',              label: "Firebringer" },
  { value: 'fireproof',             label: "Fireproof" },
  { value: 'aflame',                label: "Firestarter" },
  { value: 'nastyteeth',            label: "First Wargare" },
  { value: 'knightslayer',          label: "Focus" },
  { value: 'taurosbond',            label: "For The Herd" },
  { value: 'queensgrace',           label: "For the People" },
  { value: 'reinforced',            label: "Fortitude" },
  { value: 'frenzy',                label: "Frenzy" },
  { value: 'fireheart',             label: "From Ashes" },
  { value: 'undeadbond',            label: "From Bones" },
  { value: 'magicheart',            label: "From Dark" },
  { value: 'deathtouch',            label: "From Doom" },
  { value: 'waterheart',            label: "From Ice" },
  { value: 'airheart',              label: "From Light" },
  { value: 'natureheart',           label: "From Nature" },
  { value: 'stoneheart',            label: "From Stone" },
  { value: 'frozensoul',            label: "Frostbite" },
  { value: 'chilltouch',            label: "Frozen Hatred" },
  { value: 'frozensoul',            label: "Frozen Soul" },
  { value: 'fullplate',             label: "Full Plate" },
  { value: 'airspirit',             label: "Gale Force" },
  { value: 'gateguardian',          label: "Gate Guardian" },
  { value: 'leader',                label: "General" },
  { value: 'divineshield',          label: "Get Behind Me!" },
  { value: 'giantbond',             label: "Giant Bond" },
  { value: 'goblord',               label: "Giant Lord" },
  { value: 'queensgrace',           label: "Giant Queen" },
  { value: 'giantbond',             label: "Giant Shield" },
  { value: 'giantslayer',           label: "Giant Slayer" },
  { value: 'fireheart',             label: "Gift of Fire" },
  { value: 'undeadbond',            label: "Gloom" },
  { value: 'goblinbond',            label: "Goblin Bond" },
  { value: 'goblinbond',            label: "Goblin Friend" },
  { value: 'goblinbond',            label: "Goblin Shield" },
  { value: 'goblinslayer',          label: "Goblin Slayer" },
  { value: 'goblord',               label: "Goblord" },
  { value: 'daemonslayer',          label: "Godslayer" },
  { value: 'taurosbond',            label: "Golem Protector" },
  { value: 'graniteskin',           label: "Granite Skin" },
  { value: 'greedy',                label: "Greedy" },
  { value: 'virulence',             label: "Grim Curse" },
  { value: 'grudge',                label: "Grudge" },
  { value: 'hacknslash',            label: "Hack n Slash" },
  { value: 'dwarfbond',             label: "Hammer Mastery" },
  { value: 'airheart',              label: "Harpy Flock" },
  { value: 'darkfall',              label: "Harvest Moon" },
  { value: 'stalker',               label: "Haunted Weave" },
  { value: 'soullegion',            label: "Head Hunter" },
  { value: 'naturespirit',          label: "Healing Herb" },
  { value: 'fierycloak',            label: "Heatwave" },
  { value: 'fierycloak',            label: "Hellsteed" },
  { value: 'darkchannel',           label: "Hidden Trap" },
  { value: 'mysticbond',            label: "High Ancestry" },
  { value: 'waterlink',             label: "High Seas" },
  { value: 'armored',               label: "Holy Armor" },
  { value: 'huge',                  label: "Huge" },
  { value: 'humanbond',             label: "Human Bond" },
  { value: 'humanbond',             label: "Human Shield" },
  { value: 'humanslayer',           label: "Human Slayer" },
  { value: 'hunger',                label: "Hunger" },
  { value: 'stryxslayer',           label: "Hunt" },
  { value: 'darkfall',              label: "Hunter's Moon" },
  { value: 'chilltouch',            label: "Ice Armor" },
  { value: 'frozensoul',            label: "Ice Aura" },
  { value: 'icycloak',              label: "Icy Cloak" },
  { value: 'waterbrand',            label: "Icy Death" },
  { value: 'chilltouch',            label: "Icy Rebirth" },
  { value: 'waterbrand',            label: "Icy Veil" },
  { value: 'immense',               label: "Immense" },
  { value: 'immortal',              label: "Immortal" },
  { value: 'immune',                label: "Immune" },
  { value: 'shatter',               label: "Impact" },
  { value: 'impervious',            label: "Impervious" },
  { value: 'indigestible',          label: "Indigestible" },
  { value: 'aflame',                label: "Infernal Armor" },
  { value: 'immense',               label: "Insane Growth" },
  { value: 'inscribed',             label: "Inscribed" },
  { value: 'queensgrace',           label: "Inspiration" },
  { value: 'sunshine',              label: "Inspire Hope" },
  { value: 'insulated',             label: "Insulated" },
  { value: 'mechslayer',            label: "Invention" },
  { value: 'naturespirit',          label: "Invigorated" },
  { value: 'impervious',            label: "Invulnerable" },
  { value: 'nastyteeth',            label: "Jaws" },
  { value: 'jinx',                  label: "Jinx" },
  { value: 'hunger',                label: "Just a Bite" },
  { value: 'aspectofdeath',         label: "King's Legion" },
  { value: 'kingswill',             label: "King's Will" },
  { value: 'avenger',               label: "Knife Throwing" },
  { value: 'knightbond',            label: "Knight Bond" },
  { value: 'knightbond',            label: "Knight Shield" },
  { value: 'knightslayer',          label: "Knight Slayer" },
  { value: 'knockout',              label: "Knockout" },
  { value: 'leader',                label: "Leader" },
  { value: 'armored',               label: "Leading Light" },
  { value: 'lethaltoxin',           label: "Lethal Toxin" },
  { value: 'lifedrain',             label: "Life Drain" },
  { value: 'lifedrain',             label: "Life Siphon" },
  { value: 'greedy',                label: "Light Fingers" },
  { value: 'merfolkbond',           label: "Lightbringer" },
  { value: 'airbrand',              label: "Lightning Bolt" },
  { value: 'airbrand',              label: "Lightning Strike" },
  { value: 'lionstrength',          label: "Lion's Wrath" },
  { value: 'lionstrength',          label: "Lord of Beasts" },
  { value: 'aspectofdeath',         label: "Lord of Death" },
  { value: 'airlink',               label: "Lord of Storms" },
  { value: 'dragonslayer',          label: "Loyal Mount" },
  { value: 'dwarfbond',             label: "Mace of Power" },
  { value: 'mysticbond',            label: "Mage Lord" },
  { value: 'eyeofkhetar',           label: "Magic Aura" },
  { value: 'magicbrand',            label: "Magic Brand" },
  { value: 'magicheart',            label: "Magic Heart" },
  { value: 'magiclink',             label: "Magic Link" },
  { value: 'magicspirit',           label: "Magic Spirit" },
  { value: 'dragonvines',           label: "Magic Vines" },
  { value: 'insulated',             label: "Magical Shield" },
  { value: 'manashield',            label: "Mana Shield" },
  { value: 'empowered',             label: "Mana Source" },
  { value: 'humanbond',             label: "Manifestation" },
  { value: 'manyheads',             label: "Many Heads" },
  { value: 'marauderbond',          label: "Marauder Bond" },
  { value: 'marauderslayer',        label: "Marauder Slayer" },
  { value: 'constructbond',         label: "Master Builder" },
  { value: 'mechbond',              label: "Mech Bond" },
  { value: 'mechbond',              label: "Mech Shield" },
  { value: 'mechslayer',            label: "Mech Slayer" },
  { value: 'aspectofdeath',         label: "Mega-Aspect of Death" },
  { value: 'divineshield',          label: "Mega-Divine Right" },
  { value: 'immense',               label: "Mega-Immense" },
  { value: 'thorns',                label: "Mega-Thorns" },
  { value: 'immense',               label: "Mega-Unbreakable" },
  { value: 'winterveil',            label: "Mega-Winter Veil" },
  { value: 'magiclink',             label: "Mentor" },
  { value: 'merchant',              label: "Merchant" },
  { value: 'merfolkbond',           label: "Merfolk Bond" },
  { value: 'merfolkbond',           label: "Merfolk Shield" },
  { value: 'merfolkslayer',         label: "Merfolk Slayer" },
  { value: 'miasma',                label: "Miasma" },
  { value: 'molten',                label: "Molten" },
  { value: 'merchant',              label: "Moneybags" },
  { value: 'spiritfire',            label: "Monkey Magic" },
  { value: 'monsterbond',           label: "Monster Bond" },
  { value: 'monsterbond',           label: "Monster Shield" },
  { value: 'monsterslayer',         label: "Monster Slayer" },
  { value: 'manyheads',             label: "Monstrous Kin" },
  { value: 'regeneration',          label: "Mutant Regeneration" },
  { value: 'mysticbond',            label: "Mystic Bond" },
  { value: 'magicspirit',           label: "Mystic Channel" },
  { value: 'mysticbond',            label: "Mystic Shield" },
  { value: 'mysticslayer',          label: "Mystic Slayer" },
  { value: 'nagabond',              label: "Naga Bond" },
  { value: 'nagabond',              label: "Naga Shield" },
  { value: 'nagaslayer',            label: "Naga Slayer" },
  { value: 'nastyteeth',            label: "Nasty Teeth" },
  { value: 'thorns',                label: "Nature Aura" },
  { value: 'naturebrand',           label: "Nature Brand" },
  { value: 'natureheart',           label: "Nature Heart" },
  { value: 'naturelink',            label: "Nature Link" },
  { value: 'elfbond',               label: "Nature Pact" },
  { value: 'naturespirit',          label: "Nature Spirit" },
  { value: 'naturebrand',           label: "Nature's Death" },
  { value: 'naturelink',            label: "Nature’s Aura" },
  { value: 'naturelink',            label: "Nature’s Will" },
  { value: 'aspectofdeath',         label: "Necro Master" },
  { value: 'necromancy',            label: "Necromancy" },
  { value: 'flying',                label: "Nimble" },
  { value: 'frozensoul',            label: "Northern Clans" },
  { value: 'avenger',               label: "Ocean’s Trident" },
  { value: 'jinx',                  label: "Omen of Dark" },
  { value: 'undeadslayer',          label: "Omen of Death" },
  { value: 'firelink',              label: "Omen of Fire" },
  { value: 'chilltouch',            label: "Omen of Ice" },
  { value: 'elementalbond',         label: "Omen of Light" },
  { value: 'naturespirit',          label: "Omen of Nature" },
  { value: 'stonebrand',            label: "Omen of Stone" },
  { value: 'armored',               label: "Orc Armor" },
  { value: 'orcbond',               label: "Orc Bond" },
  { value: 'magiclink',             label: "Orc Cunning" },
  { value: 'marauderslayer',        label: "Orc Fury" },
  { value: 'goblinbond',            label: "Orc Might" },
  { value: 'orcbond',               label: "Orc Shield" },
  { value: 'orcslayer',             label: "Orc Slayer" },
  { value: 'orclord',               label: "Orclord" },
  { value: 'clockwork',             label: "Overclock" },
  { value: 'wildfolkslayer',        label: "Pack Master" },
  { value: 'darkfall',              label: "Penumbra" },
  { value: 'trueshot',              label: "Perfect Aim" },
  { value: 'merchant',              label: "Pickpocket" },
  { value: 'graniteskin',           label: "Pillage and Plunder" },
  { value: 'plaguetouch',           label: "Plague Touch" },
  { value: 'virulence',             label: "Plaguebearer" },
  { value: 'aspectofplague',        label: "Poison Gaze" },
  { value: 'jinx',                  label: "Poison Spores" },
  { value: 'waterlink',             label: "Poison Tide" },
  { value: 'divineaura',            label: "Portent" },
  { value: 'spiritfire',            label: "Possession" },
  { value: 'immune',                label: "Potion of Armor" },
  { value: 'immune',                label: "Potion of Blessing" },
  { value: 'immune',                label: "Potion of Enchantment" },
  { value: 'immune',                label: "Potion of Explosion" },
  { value: 'immune',                label: "Potion of Rejuvenation" },
  { value: 'immune',                label: "Potion of Shielding" },
  { value: 'humanslayer',           label: "Precision" },
  { value: 'lionstrength',          label: "Pride Prowess" },
  { value: 'stoneskin',             label: "Protector" },
  { value: 'nastyteeth',            label: "Provocation" },
  { value: 'blessed',               label: "Purification" },
  { value: 'pyromania',             label: "Pyromania" },
  { value: 'queensgrace',           label: "Queen's Grace" },
  { value: 'grudge',                label: "Quick Study" },
  { value: 'divineshield',          label: "Radiant Aura" },
  { value: 'goblord',               label: "Raging Bull" },
  { value: 'spiritfire',            label: "Rainbow Link" },
  { value: 'rakshabond',            label: "Raksha Bond" },
  { value: 'rakshabond',            label: "Raksha Shield" },
  { value: 'rakshaslayer',          label: "Raksha Slayer" },
  { value: 'nastyteeth',            label: "Rancor" },
  { value: 'constructbond',         label: "Razor Armor" },
  { value: 'nagaslayer',            label: "Razor Teeth" },
  { value: 'undeadslayer',          label: "Reaper" },
  { value: 'immortal',              label: "Rebirth" },
  { value: 'regeneration',          label: "Regeneration" },
  { value: 'reinforced',            label: "Reinforced" },
  { value: 'reinforced',            label: "Repair" },
  { value: 'magicbrand',            label: "Resilience" },
  { value: 'stoneheart',            label: "Resplendence" },
  { value: 'frenzy',                label: "Revenge" },
  { value: 'blessed',               label: "Revered" },
  { value: 'darkfall',              label: "Rising Shadows" },
  { value: 'stonelink',             label: "Rock Solid" },
  { value: 'stonebrand',            label: "Rocky Death" },
  { value: 'roguebond',             label: "Rogue Bond" },
  { value: 'roguebond',             label: "Rogue Shield" },
  { value: 'rogueslayer',           label: "Rogue Slayer" },
  { value: 'snare',                 label: "Root Trap" },
  { value: 'avenger',               label: "Royal Armory" },
  { value: 'sacrifice',             label: "Sacrifice" },
  { value: 'impervious',            label: "Savior" },
  { value: 'queensgrace',           label: "Second Helping" },
  { value: 'seedling',              label: "Seedling" },
  { value: 'feyslayer',             label: "Serendipity" },
  { value: 'blessed',               label: "Serenity" },
  { value: 'aspectofdeath',         label: "Serpent's Fang" },
  { value: 'insulated',             label: "Shadow Scales" },
  { value: 'stealthy',              label: "Shadows’ Call" },
  { value: 'shatter',               label: "Shatter" },
  { value: 'arcane',                label: "Shining Staff" },
  { value: 'airbrand',              label: "Shock" },
  { value: 'molten',                label: "Shrapnel" },
  { value: 'siege',                 label: "Siege" },
  { value: 'siege',                 label: "Siegebreaker" },
  { value: 'silence',               label: "Silence!" },
  { value: 'siphon',                label: "Siphon" },
  { value: 'undeadslayer',          label: "Skull Death" },
  { value: 'blessed',               label: "Sky Ancestry" },
  { value: 'slippery',              label: "Slippery" },
  { value: 'chill',                 label: "Snap Freeze" },
  { value: 'snare',                 label: "Snare" },
  { value: 'sacrifice',             label: "Sneak Attack" },
  { value: 'frozensoul',            label: "Snowstorm" },
  { value: 'ward',                  label: "Soaring" },
  { value: 'undeadbond',            label: "Song of Bones" },
  { value: 'inscribed',             label: "Song of Darkness" },
  { value: 'daemonslayer',          label: "Song of Doom" },
  { value: 'firebrand',             label: "Song of Fire" },
  { value: 'magicheart',            label: "Song of Ice" },
  { value: 'blessed',               label: "Song of Light" },
  { value: 'naturelink',            label: "Song of Nature" },
  { value: 'stonelink',             label: "Song of Stone" },
  { value: 'airheart',              label: "Soul Caller" },
  { value: 'soullegion',            label: "Soul Legion" },
  { value: 'soullegion',            label: "Soul Ritual" },
  { value: 'aspectofplague',        label: "Sour Candy" },
  { value: 'mysticbond',            label: "Spark" },
  { value: 'dragonslayer',          label: "Spawn" },
  { value: 'daemonicpact',          label: "Spawn of Hell" },
  { value: 'reinforced',            label: "Spell Armor" },
  { value: 'inscribed',             label: "Spell Block" },
  { value: 'spikearmor',            label: "Spiked Armor" },
  { value: 'spikearmor',            label: "Spiky" },
  { value: 'airbrand',              label: "Spiny" },
  { value: 'miasma',                label: "Spore Cloud" },
  { value: 'stalker',               label: "Stalker" },
  { value: 'stealthy',              label: "Stealthy" },
  { value: 'graniteskin',           label: "Stone Aura" },
  { value: 'stonebrand',            label: "Stone Brand" },
  { value: 'stonespirit',           label: "Stone Circle" },
  { value: 'stoneheart',            label: "Stone Heart" },
  { value: 'stonelink',             label: "Stone Link" },
  { value: 'divineshield',          label: "Stone Loyalty" },
  { value: 'stonebrand',            label: "Stone Mastery" },
  { value: 'stonespirit',           label: "Stone Spirit" },
  { value: 'stonespirit',           label: "Stone Wall" },
  { value: 'stoneskin',             label: "Stoneskin" },
  { value: 'airheart',              label: "Storm Aura" },
  { value: 'fierycloak',            label: "Storm Flock" },
  { value: 'divineshield',          label: "Storm Shield" },
  { value: 'icycloak',              label: "Storm Soul" },
  { value: 'airbrand',              label: "Stormy Hatred" },
  { value: 'stryxbond',             label: "Stryx Bond" },
  { value: 'flying',                label: "Stryx Commander" },
  { value: 'stryxbond',             label: "Stryx Shield" },
  { value: 'stryxslayer',           label: "Stryx Slayer" },
  { value: 'sturdy',                label: "Sturdy" },
  { value: 'aspectofdeath',         label: "Succumb" },
  { value: 'elementalslayer',       label: "Sudden Doom" },
  { value: 'fierycloak',            label: "Summer Veil" },
  { value: 'sunshine',              label: "Sun Fire" },
  { value: 'fierycloak',            label: "Sun Flare" },
  { value: 'sunshine',              label: "Sun's Glory" },
  { value: 'sunshine',              label: "Sunshine" },
  { value: 'suppression',           label: "Suppression" },
  { value: 'fast',                  label: "Swift" },
  { value: 'cursed',                label: "Swift Curse" },
  { value: 'magicspirit',           label: "Tactician" },
  { value: 'naturebrand',           label: "Tangle" },
  { value: 'taurosbond',            label: "Tauros Bond" },
  { value: 'taurosbond',            label: "Tauros Shield" },
  { value: 'taurosslayer',          label: "Tauros Slayer" },
  { value: 'technomancy',           label: "Technomancy" },
  { value: 'doom',                  label: "Temptation" },
  { value: 'thorns',                label: "Tentacles" },
  { value: 'thickhead',             label: "Thick Head" },
  { value: 'beastbond',             label: "Thick Hide" },
  { value: 'mechbond',              label: "Thieves’ Guild" },
  { value: 'thorns',                label: "Thorns" },
  { value: 'knockout',              label: "Thunder Fist" },
  { value: 'waterspirit',           label: "Tidal King" },
  { value: 'big',                   label: "Titanic Surge" },
  { value: 'dragonbond',            label: "Tough Scales" },
  { value: 'venomous',              label: "Toxic" },
  { value: 'immune',                label: "Toxic Hatred" },
  { value: 'inscribed',             label: "Transcend" },
  { value: 'natureheart',           label: "Tree of Knowledge" },
  { value: 'regeneration',          label: "Troll Regeneration" },
  { value: 'trueshot',              label: "True Shot" },
  { value: 'waterspirit',           label: "Tsunami" },
  { value: 'immense',               label: "Unbreakable" },
  { value: 'undeadbond',            label: "Undead Bond" },
  { value: 'undeadbond',            label: "Undead Shield" },
  { value: 'undeadslayer',          label: "Undead Slayer" },
  { value: 'undeadslayer',          label: "Undying" },
  { value: 'undeadbond',            label: "Unholy Blessing" },
  { value: 'ensoul',                label: "Unstable Possession" },
  { value: 'firebrand',             label: "Up in Flames" },
  { value: 'beastbond',             label: "Urska Bond" },
  { value: 'beastslayer',           label: "Urska Major" },
  { value: 'beastslayer',           label: "Urska Shield" },
  { value: 'beastslayer',           label: "Urska Slayer" },
  { value: 'stoneheart',            label: "Valuable" },
  { value: 'insulated',             label: "Vanguard" },
  { value: 'daemonslayer',          label: "Vengeance" },
  { value: 'venomous',              label: "Venomous" },
  { value: 'gardswrath',            label: "Victory Lap" },
  { value: 'lionstrength',          label: "Virtue of Courage" },
  { value: 'divineshield',          label: "Virtue of Honor" },
  { value: 'compassion',            label: "Virtue of Humility" },
  { value: 'hacknslash',            label: "Virtue of Justice" },
  { value: 'fullplate',             label: "Virtue of Loyalty" },
  { value: 'ensoul',                label: "Virtue of Sacrifice" },
  { value: 'virulence',             label: "Virulence" },
  { value: 'hunger',                label: "Voracious" },
  { value: 'naturebrand',           label: "Wall of Vines" },
  { value: 'ward',                  label: "Ward" },
  { value: 'warded',                label: "Warded" },
  { value: 'wargarebond',           label: "Wargare Bond" },
  { value: 'wargarebond',           label: "Wargare Shield" },
  { value: 'wargareslayer',         label: "Wargare Slayer" },
  { value: 'waterbrand',            label: "Water Brand" },
  { value: 'waterheart',            label: "Water Heart" },
  { value: 'waterlink',             label: "Water Link" },
  { value: 'waterspirit',           label: "Water Mastery" },
  { value: 'waterspirit',           label: "Water Spirit" },
  { value: 'waterbrand',            label: "Watery Binding" },
  { value: 'cocoon',                label: "Webweaver" },
  { value: 'empowered',             label: "Well-Read" },
  { value: 'wildfolkbond',          label: "Wild Frenzy" },
  { value: 'beastbond',             label: "Wild Growth" },
  { value: 'dragonvines',           label: "Wild Mana" },
  { value: 'thorns',                label: "Wild Vines" },
  { value: 'wildfolkbond',          label: "Wildfolk Bond" },
  { value: 'wildfolkbond',          label: "Wildfolk Shield" },
  { value: 'wildfolkslayer',        label: "Wildfolk Slayer" },
  { value: 'winterveil',            label: "Wind Aura" },
  { value: 'manashield',            label: "Wind Shield" },
  { value: 'airheart',              label: "Wind Speed" },
  { value: 'winterveil',            label: "Winter Veil" },
  { value: 'natureheart',           label: "Wood Ancestry" },
  { value: 'fierycloak',            label: "Wrath of Anu" },
  { value: 'doom',                  label: "Zorn's Fury" }
];